<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- common packages -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.VisualStudio.Validation" Version="17.13.22" />
    <PackageVersion Include="Roslynator.Analyzers" Version="4.14.1" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
  </ItemGroup>
  
  <!-- src packages -->
  <ItemGroup>
    <PackageVersion Include="AWS.Extensions" Version="1.5.26.1" />
    <PackageVersion Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.3.7" />
    <PackageVersion Include="AWSSDK.SecretsManager" Version="4.0.1.9" />
    <PackageVersion Include="Elastic.CommonSchema.Serilog" Version="9.0.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21"/>
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.21"/>
    <PackageVersion Include="Microsoft.AspNetCore.HeaderPropagation" Version="8.0.21" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21"/>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Analyzers" Version="9.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10" />
    <PackageVersion Include="Microsoft.Identity.Web" Version="3.0.0"/>
    <PackageVersion Include="Microsoft.Identity.Web.DownstreamApi" Version="3.0.0"/>
    <PackageVersion Include="MongoDB.Driver" Version="3.5.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.2" />
    <PackageVersion Include="Serilog.Enrichers.ClientInfo" Version="2.1.2" />
    <PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="8.0.2" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="8.1.4"/>
    <PackageVersion Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
  </ItemGroup>

  <!-- test packages -->
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="6.12.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.8" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.0" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>
</Project>